apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: frontend
        image: todo-frontend:latest
        imagePullPolicy: Never    # <--- YEH FIX HAI
        env:
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: NEXT_PUBLIC_API_URL
          value: "http://todo-app-backend:8000"
        ports:
        - containerPort: 3000